<?php

return [
    [
        "city_key" => "fy",
        "city_name" => "阜阳",
        "city_py" => "fuyang",
        "city_x" => "115.82729",
        "city_y" => "32.898866",
//        "city_api" => "2",
//        "city_isHot" => 1,
//        "city_HotSort" => "12",
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "hn",
        "city_name" => "海宁",
        "city_py" => "haining",
        "city_x" => "120.69",
        "city_y" => "30.53",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "hrb",
        "city_name" => "哈尔滨",
        "city_py" => "haerbin",
        "city_x" => "126.632538",
        "city_y" => "45.761296",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "hy",
        "city_name" => "海盐",
        "city_py" => "haiyan",
        "city_x" => "118.75",
        "city_y" => "30.95",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "jx",
        "city_name" => "嘉兴",
        "city_py" => "jiaxing",
        "city_x" => "120.760103",
        "city_y" => "30.749982",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "lz",
        "city_name" => "兰州",
        "city_py" => "lanzhou",
        "city_x" => "103.843316",
        "city_y" => "36.040352",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "mianyang",
        "city_name" => "绵阳",
        "city_py" => "mianyang",
        "city_x" => "104.676198",
        "city_y" => "31.475592",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "la",
        "city_name" => "六安",
        "city_py" => "luan",
        "city_x" => "116.505253",
        "city_y" => "31.755558",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "wlmq",
        "city_name" => "乌鲁木齐",
        "city_py" => "wulumuqi",
        "city_x" => "87.605492",
        "city_y" => "43.831974",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "xx",
        "city_name" => "新乡",
        "city_py" => "xinxiang",
        "city_x" => "113.906593",
        "city_y" => "35.301957",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],

    [
        "city_key" => "zunyi",
        "city_name" => "遵义",
        "city_py" => "zunyi",
        "city_x" => "106.928387",
        "city_y" => "27.688544",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "nj",
        "city_name" => "南京",
        "city_py" => "nanjing",
        "city_x" => "118.78315",
        "city_y" => "32.030781",
//        "city_api" => "1",
//        "city_isHot" => 1,
//        "city_HotSort" => "1",
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "hf",
        "city_name" => "合肥",
        "city_py" => "hefei",
        "city_x" => "117.272818",
        "city_y" => "31.860853",
//        "city_api" => "1",
//        "city_isHot" => 1,
//        "city_HotSort" => "2",
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "wx",
        "city_name" => "无锡",
        "city_py" => "wuxi",
        "city_x" => "120.305456",
        "city_y" => "31.570037",
//        "city_api" => "1",
//        "city_isHot" => 1,
//        "city_HotSort" => "6",
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "wh",
        "city_name" => "芜湖",
        "city_py" => "wuhu",
        "city_x" => "118.369956",
        "city_y" => "31.331325",
//        "city_api" => "1",
//        "city_isHot" => 1,
//        "city_HotSort" => "3",
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "hz",
        "city_name" => "杭州",
        "city_py" => "hangzhou",
        "city_x" => "120.169825",
        "city_y" => "30.276775",
//        "city_api" => "1",
//        "city_isHot" => 1,
//        "city_HotSort" => "5",
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "cz",
        "city_name" => "常州",
        "city_py" => "changzhou",
        "city_x" => "119.992676",
        "city_y" => "31.739847",
//        "city_api" => "1",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "sz",
        "city_name" => "苏州",
        "city_py" => "suzhou",
        "city_x" => "120.654945",
        "city_y" => "31.334285",
//        "city_api" => "1",
//        "city_isHot" => 1,
//        "city_HotSort" => "8",
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "xa",
        "city_name" => "西安",
        "city_py" => "xian",
        "city_x" => "108.947124",
        "city_y" => "34.25977",
//        "city_api" => "1",
//        "city_isHot" => 1,
//        "city_HotSort" => "7",
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "sy",
        "city_name" => "沈阳",
        "city_py" => "shenyang",
        "city_x" => "123.433971",
        "city_y" => "41.804766",
//        "city_api" => "1",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "bb",
        "city_name" => "蚌埠",
        "city_py" => "bengbu",
        "city_x" => "117.371492",
        "city_y" => "32.930102",
//        "city_api" => "2",
//        "city_isHot" => 1,
//        "city_HotSort" => "10",
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "cd",
        "city_name" => "成都",
        "city_py" => "chengdou",
        "city_x" => "104.067923",
        "city_y" => "30.679943",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "chuzhou",
        "city_name" => "滁州",
        "city_py" => "chuzhou",
        "city_x" => "118.33889",
        "city_y" => "32.309768",
//        "city_api" => "2",
//        "city_isHot" => 1,
//        "city_HotSort" => "11",
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "mas",
        "city_name" => "马鞍山",
        "city_py" => "maanshan",
        "city_x" => "118.549347",
        "city_y" => "31.693119",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "tj",
        "city_name" => "天津",
        "city_py" => "tianjin",
        "city_x" => "117.170563",
        "city_y" => "39.166537",
//        "city_api" => "2",
//        "city_isHot" => 1,
//        "city_HotSort" => "9",
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "tz",
        "city_name" => "泰州",
        "city_py" => "taizhou",
        "city_x" => "119.919606",
        "city_y" => "32.476053",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "xz",
        "city_name" => "徐州",
        "city_py" => "xuzhou",
        "city_x" => "117.192219",
        "city_y" => "34.269186",
//        "city_api" => "2",
//        "city_isHot" => 1,
//        "city_HotSort" => "4",
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "yc",
        "city_name" => "盐城",
        "city_py" => "yancheng",
        "city_x" => "120.143738",
        "city_y" => "33.36222",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "yz",
        "city_name" => "扬州",
        "city_py" => "yangzhou",
        "city_x" => "119.427778",
        "city_y" => "32.408505",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "sh",
        "city_name" => "上海",
        "city_py" => "shanghai",
        "city_x" => "121.47479",
        "city_y" => "31.236423",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "cq",
        "city_name" => "重庆",
        "city_py" => "chongqing",
        "city_x" => "106.55096",
        "city_y" => "29.569499",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "aq",
        "city_name" => "安庆",
        "city_py" => "anqing",
        "city_x" => "117.03495",
        "city_y" => "30.64825",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "bd",
        "city_name" => "保定",
        "city_py" => "baoding",
        "city_x" => "115.49798",
        "city_y" => "38.859494",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "nt",
        "city_name" => "南通",
        "city_py" => "nantong",
        "city_x" => "120.864716",
        "city_y" => "32.017683",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "jy",
        "city_name" => "江阴",
        "city_py" => "jiangying",
        "city_x" => "120.280037",
        "city_y" => "31.911662",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "yx",
        "city_name" => "宜兴",
        "city_py" => "yixing",
        "city_x" => "119.818779",
        "city_y" => "31.366189",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "fz",
        "city_name" => "福州",
        "city_py" => "fuzhou",
        "city_x" => "119.296389",
        "city_y" => "26.074268",
//        "city_api" => "2",
//        "city_isHot" => 0,
//        "city_HotSort" => 0,
//        "city_zoom" => 13,
//        "city_dist_zoom" => 12
    ],
    [
        "city_key" => "zj",
        "city_name" => "镇江",
        "city_py" => "zhenjaing",
        "city_x" => "119.432567",
        "city_y" => "32.197975"
    ],
    [
        "city_key" => "ha",
        "city_name" => "淮安",
        "city_py" => "huaian",
        "city_x" => "119.012981",
        "city_y" => "33.610084"
    ],
    [
        "city_key" => "jh",
        "city_name" => "金华",
        "city_py" => "jinhua",
        "city_x" => "119.644377",
        "city_y" => "29.074380"
    ],
    [
        "city_key" => "mas",
        "city_name" => "马鞍山",
        "city_py" => "maanshan",
        "city_x" => "118.510330",
        "city_y" => "31.684691"
    ],
    [
        "city_key" => "sh",
        "city_name" => "上海",
        "city_py" => "shanghai",
        "city_x" => "121.475232",
        "city_y" => "31.228731"
    ],
    [
        "city_key" => "tx",
        "city_name" => "桐乡",
        "city_py" => "tongxiang",
        "city_x" => "120.543149",
        "city_y" => "30.635190"
    ]
];
?>